package fit.iuh.dulichgiare.entity;
// Generated Feb 8, 2023, 10:55:58 AM by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel")
public class Hotel implements java.io.Serializable {

	private long id;
	private String name;
	private String address;
	private double price;
	private int star;
	private String phone;
	private String image;

	public Hotel() {
	}

	public Hotel(long id, String name, String address, double price, int star, String phone, String image) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.price = price;
		this.star = star;
		this.phone = phone;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "price", nullable = false, precision = 17, scale = 17)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "star", nullable = false)
	public int getStar() {
		return this.star;
	}

	public void setStar(int star) {
		this.star = star;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
