package fit.iuh.dulichgiare.entity;
// Generated Feb 8, 2023, 10:55:58 AM by Hibernate Tools 4.3.5.Final

import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Itinerary generated by hbm2java
 */
@Entity
@Table(name = "itinerary")
public class Itinerary implements java.io.Serializable {

	private long id;
	private Tour tour;
	private String description;
	private Set<ItineraryDetail> itinerarydetails ;

	public Itinerary() {
	}

	public Itinerary(Tour tour, String description) {
		super();
		this.tour = tour;
		this.description = description;
		
	}

	public Itinerary(long id, Tour tour, String description) {
		this.id = id;
		this.tour = tour;
		this.description = description;
	}

	public Itinerary(long id, Tour tour, String description, Set<ItineraryDetail> itinerarydetails) {
		this.id = id;
		this.tour = tour;
		this.description = description;
		this.itinerarydetails = itinerarydetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tour_id", nullable = false)
	public Tour getTour() {
		return this.tour;
	}

	public void setTour(Tour tour) {
		this.tour = tour;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itinerary")
	public Set<ItineraryDetail> getItinerarydetails() {
		return this.itinerarydetails;
	}

	public void setItinerarydetails(Set<ItineraryDetail> itinerarydetails) {
		this.itinerarydetails = itinerarydetails;
	}

}
