package fit.iuh.dulichgiare.entity;
// Generated Feb 8, 2023, 10:55:58 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "\"order\"")
public class Order implements java.io.Serializable {

	private long id;
	private Customer customer;
	private Tour tour;
	private String note;
	private int numberofadbult;
	private int numberofchildren;
	private Date createat;
	private double total;
	private String status;

	public Order() {
	}

	public Order(Customer customer, Tour tour, String note, int numberofadbult, int numberofchildren, Date createat,
			double total, String status) {
		super();
		this.customer = customer;
		this.tour = tour;
		this.note = note;
		this.numberofadbult = numberofadbult;
		this.numberofchildren = numberofchildren;
		this.createat = createat;
		this.total = total;
		this.status = status;
	}

	public Order(long id, Customer customer, Tour tour, int numberofadbult, int numberofchildren, double total,
			String status) {
		this.id = id;
		this.customer = customer;
		this.tour = tour;
		this.numberofadbult = numberofadbult;
		this.numberofchildren = numberofchildren;
		this.total = total;
		this.status = status;
	}

	public Order(long id, Customer customer, Tour tour, String note, int numberofadbult, int numberofchildren,
			Date createat, double total, String status) {
		this.id = id;
		this.customer = customer;
		this.tour = tour;
		this.note = note;
		this.numberofadbult = numberofadbult;
		this.numberofchildren = numberofchildren;
		this.createat = createat;
		this.total = total;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tour_id", nullable = false)
	public Tour getTour() {
		return this.tour;
	}

	public void setTour(Tour tour) {
		this.tour = tour;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "numberofadbult", nullable = false)
	public int getNumberofadbult() {
		return this.numberofadbult;
	}

	public void setNumberofadbult(int numberofadbult) {
		this.numberofadbult = numberofadbult;
	}

	@Column(name = "numberofchildren", nullable = false)
	public int getNumberofchildren() {
		return this.numberofchildren;
	}

	public void setNumberofchildren(int numberofchildren) {
		this.numberofchildren = numberofchildren;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createat", length = 13)
	public Date getCreateat() {
		return this.createat;
	}

	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	@Column(name = "total", nullable = false, precision = 17, scale = 17)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
