package fit.iuh.dulichgiare.entity;
// Generated Feb 8, 2023, 10:55:58 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion")
public class Promotion implements java.io.Serializable {

	private long id;
	private String name;
	private double discount;
	private Date endday;
	private Set<Tour> tours = new HashSet<Tour>(0);

	public Promotion() {
	}

	public Promotion(long id, String name, double discount, Date endday) {
		this.id = id;
		this.name = name;
		this.discount = discount;

		this.endday = endday;
	}

	public Promotion(long id, String name, double discount, Date endday, Set<Tour> tours) {
		this.id = id;
		this.name = name;
		this.discount = discount;

		this.endday = endday;
		this.tours = tours;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "discount", nullable = false, precision = 17, scale = 17)
	public double getdiscount() {
		return this.discount;
	}

	public void setdiscount(double discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endday", nullable = false, length = 13)
	public Date getEndday() {
		return this.endday;
	}

	public void setEndday(Date endday) {
		this.endday = endday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion", cascade = CascadeType.ALL)
	public Set<Tour> getTours() {
		return this.tours;
	}

	public void setTours(Set<Tour> tours) {
		this.tours = tours;
	}

}
