package fit.iuh.dulichgiare.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Tour generated by hbm2java
 */
@Entity
@Table(name = "tourdetail")

public class TourDetail implements java.io.Serializable {
	private long id;
	private String description;
	private String transport;
	private int starhotel;
	private Tour tour;

	public TourDetail() {
		super();
	}

	public TourDetail(String description, String transport, int starhotel, Tour tour) {
		super();
		this.description = description;
		this.transport = transport;
		this.starhotel = starhotel;
		this.tour = tour;
	}

	public TourDetail(long id, String description, String transport, int starhotel, Tour tour) {
		super();
		this.id = id;
		this.description = description;
		this.transport = transport;
		this.starhotel = starhotel;
		this.tour = tour;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "transport", nullable = false)
	public String getTransport() {
		return transport;
	}

	public void setTransport(String transport) {
		this.transport = transport;
	}

	@Column(name = "starhotel", nullable = false)
	public int getstarhotel() {
		return starhotel;
	}

	public void setstarhotel(int starhotel) {
		this.starhotel = starhotel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tour_id", nullable = false)
	public Tour getTour() {
		return tour;
	}

	public void setTour(Tour tour) {
		this.tour = tour;
	}

}
