package fit.iuh.dulichgiare.entity;
// Generated Feb 8, 2023, 10:55:58 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Tour generated by hbm2java
 */
@Entity
@Table(name = "tour")
public class Tour implements java.io.Serializable {

	private long id;
	private Promotion promotion;
	private TourGuide tourguide;
	private String name;
	private String image;
	private String departure;
	private String destination;
	private Date startday;
	private int numberofday;
	private int numberofpeople;
	private int subcriber;
	private String type;
	private double price;
	private Date createat;
	private int liked;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Itinerary> itineraries = new HashSet<Itinerary>(0);
	private Set<TourDetail> tourdetails = new HashSet<TourDetail>(0);

	public Tour() {
	}

	public Tour(long id, Promotion promotion, TourGuide tourguide, String name, String image, String departure,
			String destination, Date startday, int numberofday, int numberofpeople, int subcriber, String type,
			double price, Date createat, int liked) {
		this.id = id;
		this.promotion = promotion;
		this.tourguide = tourguide;
		this.name = name;
		this.image = image;
		this.departure = departure;
		this.destination = destination;
		this.startday = startday;
		this.numberofday = numberofday;
		this.numberofpeople = numberofpeople;
		this.subcriber = subcriber;
		this.type = type;
		this.price = price;
		this.createat = createat;
		this.liked = liked;
	}

	public Tour(long id, Promotion promotion, TourGuide tourguide, String name, String image, String departure,
			String destination, Date startday, int numberofday, int numberofpeople, int subcriber, String type,
			double price, Date createat, int liked, Set<Order> orders, Set<Itinerary> itineraries,
			Set<TourDetail> tourdetails) {
		super();
		this.id = id;
		this.promotion = promotion;
		this.tourguide = tourguide;
		this.name = name;
		this.image = image;
		this.departure = departure;
		this.destination = destination;
		this.startday = startday;
		this.numberofday = numberofday;
		this.numberofpeople = numberofpeople;
		this.subcriber = subcriber;
		this.type = type;
		this.price = price;
		this.createat = createat;
		this.liked = liked;
		this.orders = orders;
		this.itineraries = itineraries;
		this.tourdetails = tourdetails;
	}

	public Tour(Promotion promotion, TourGuide tourguide, String name, String image, String departure,
			String destination, Date startday, int numberofday, int numberofpeople, int subcriber, String type,
			double price, Date createat, int liked) {
		super();
		this.promotion = promotion;
		this.tourguide = tourguide;
		this.name = name;
		this.image = image;
		this.departure = departure;
		this.destination = destination;
		this.startday = startday;
		this.numberofday = numberofday;
		this.numberofpeople = numberofpeople;
		this.subcriber = subcriber;
		this.type = type;
		this.price = price;
		this.createat = createat;
		this.liked = liked;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id", nullable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tourguide_id", nullable = false)
	public TourGuide getTourguide() {
		return this.tourguide;
	}

	public void setTourguide(TourGuide tourguide) {
		this.tourguide = tourguide;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "departure", nullable = false)
	public String getDeparture() {
		return this.departure;
	}

	public void setDeparture(String departure) {
		this.departure = departure;
	}

	@Column(name = "destination", nullable = false)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startday", nullable = false, length = 13)
	public Date getStartday() {
		return this.startday;
	}

	public void setStartday(Date startday) {
		this.startday = startday;
	}

	@Column(name = "numberofday", nullable = false)
	public int getNumberofday() {
		return this.numberofday;
	}

	public void setNumberofday(int numberofday) {
		this.numberofday = numberofday;
	}

	@Column(name = "numberofpeople", nullable = false)
	public int getNumberofpeople() {
		return this.numberofpeople;
	}

	public void setNumberofpeople(int numberofpeople) {
		this.numberofpeople = numberofpeople;
	}

	@Column(name = "subcriber", nullable = false)
	public int getSubcriber() {
		return this.subcriber;
	}

	public void setSubcriber(int subcriber) {
		this.subcriber = subcriber;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "price", nullable = false, precision = 17, scale = 17)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createat", nullable = false, length = 13)
	public Date getCreateat() {
		return this.createat;
	}

	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	@Column(name = "liked", nullable = false)
	public int getliked() {
		return this.liked;
	}

	public void setliked(int liked) {
		this.liked = liked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
	public Set<Itinerary> getItineraries() {
		return this.itineraries;
	}

	public void setItineraries(Set<Itinerary> itineraries) {
		this.itineraries = itineraries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
	public Set<TourDetail> getTourdetails() {
		return tourdetails;
	}

	public void setTourdetails(Set<TourDetail> tourdetails) {
		this.tourdetails = tourdetails;
	}

}
